# Site settings
title: run
email: ward.muylaert@gmail.com
timezone: UTC
description: > # this means to ignore newlines until "baseurl:"
  Anything that I find interesting enough to relate to my running.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://run.wxm.be" # the base hostname & protocol for your site
author: Ward Muylaert

# Social
strava_username: wardmuylaert
smashrun_username: ward
rss: RSS

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
  - publish.sh
