# Site settings
title: run
email: ward@wardje.eu
timezone: UTC
description: > # this means to ignore newlines until "baseurl:"
  Anything that I find interesting enough to relate to my running.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
author: Ward Muylaert
social:
  strava: 1091838
  smashrun: ward
  runkeeper: wardmuylaert

# Build settings
markdown: kramdown
