# Site settings
title: run
email: ward@wardje.eu
timezone: UTC
description: > # this means to ignore newlines until "baseurl:"
  Anything that I find interesting enough to relate to my running.
baseurl: "/run" # the subpath of your site, e.g. /blog/
url: "http://wardje.eu" # the base hostname & protocol for your site
author: Ward Muylaert
social:
  strava: wardmuylaert
  smashrun: ward
  runkeeper: wardmuylaert

# Build settings
markdown: kramdown
exclude: ['publish.sh']
