# Site settings
title: run
email: ward.muylaert@gmail.com
timezone: UTC
description: > # this means to ignore newlines until "baseurl:"
  Anything that I find interesting enough to relate to my running.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://run.wxm.be" # the base hostname & protocol for your site
author: Ward Muylaert
social:
  strava: wardmuylaert
  smashrun: ward
# Do not show runkeeper
#  runkeeper: wardmuylaert

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
  - publish.sh
